name: Setup Workspace
description: Clone repo and setup Python
inputs:
  dependency-group:
    required: true
    description: The dependency group to install

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install --system .[${{ dependency-group }}]
      shell: bash